title:              poruszając poezję
email:              magdalenamj@fastmail.com
description:        relacja z procesu wprawiania w ruch wierszy Nuali Ní Dhomhnaill
author:             Magdalena Mak-Jeszka
baseurl:            ""
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:
github_username:
facebook_username:
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
